-- 코드를 입력하세요
# WITH ORDERS AS (
#     SELECT ORDER_ID, PRODUCT_ID,
#     CASE
#         WHEN OUT_DATE IS NULL THEN ""
#         ELSE OUT_DATE
#     END AS OUT_DATE
#     FROM FOOD_ORDER
# )
SELECT ORDER_ID, PRODUCT_ID,DATE_FORMAT(OUT_DATE,"%Y-%m-%d") AS OUT_DATE,
    (CASE
        WHEN OUT_DATE <= 20220501 THEN "출고완료"
        WHEN OUT_DATE > 20220501 THEN "출고대기"
        WHEN OUT_DATE IS NULL THEN "출고미정"
    END) AS 출고여부
    FROM FOOD_ORDER
    ORDER BY ORDER_ID

# WHERE
# GROUP BY
# HAVING
# ORDER BY
# LIMIT