-- 코드를 작성해주세요

SELECT E.ID, (
    CASE
        WHEN E.RAN<=0.25 THEN "CRITICAL"
        WHEN E.RAN<=0.5 THEN "HIGH"
        WHEN E.RAN<=0.75 THEN "MEDIUM"
        ELSE "LOW"
    END
) AS COLONY_NAME
FROM (
    SELECT ID, PERCENT_RANK() OVER(
        ORDER BY SIZE_OF_COLONY DESC
    ) AS RAN
    FROM ECOLI_DATA
) E
ORDER BY E.ID