-- 코드를 작성해주세요
SELECT ED.ID, (
    CASE
        WHEN ED2.R<=0.25 THEN "CRITICAL"
        WHEN ED2.R<=0.5 THEN "HIGH"
        WHEN ED2.R<=0.75 THEN "MEDIUM"
        ELSE "LOW"
    END
)AS COLONY_NAME
FROM ECOLI_DATA ED
JOIN (
    SELECT ID, PERCENT_RANK() OVER(
    ORDER BY SIZE_OF_COLONY DESC
    ) AS R
    FROM ECOLI_DATA
)ED2 ON ED.ID = ED2.ID
ORDER BY ID
