-- 코드를 작성해주세요

SELECT E.ID, (
CASE
    WHEN E.COLONY_NAME <= 0.25 THEN "CRITICAL"
    WHEN E.COLONY_NAME <= 0.5 THEN "HIGH"
    WHEN E.COLONY_NAME <= 0.75 THEN "MEDIUM"
    ELSE "LOW" 
END
) AS COLONY_NAME
FROM(
    SELECT ID, PERCENT_RANK() OVER(
    ORDER BY SIZE_OF_COLONY DESC
    ) AS COLONY_NAME
    FROM ECOLI_DATA 
) E
ORDER BY E.ID

# WHERE
# GROUP BY
# HAVING
# ORDER BY
# LIMIT