-- 코드를 작성해주세요
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPER_INFOS
WHERE CONCAT(IFNULL(SKILL_1,''), IFNULL(SKILL_2,''), IFNULL(SKILL_3,'')) LIKE "%Python%"
ORDER BY ID


# WHERE
# GROUP BY
# HAVING
# ORDER BY
# LIMIT