SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, D.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM PATIENT P 
JOIN APPOINTMENT A ON P.PT_NO = A.PT_NO
JOIN DOCTOR D ON D.DR_ID = A.MDDR_ID
WHERE A.APNT_YMD >= 20220413 AND A.APNT_YMD < 20220414
AND A.MCDP_CD LIKE "CS" AND A.APNT_CNCL_YN LIKE "N"
ORDER BY A.APNT_YMD