-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME, B.PRICE
FROM (
    SELECT WRITER_ID, SUM(PRICE) AS PRICE, STATUS
    FROM USED_GOODS_BOARD 
    WHERE STATUS LIKE "DONE"
    GROUP BY WRITER_ID
    HAVING PRICE >= 700000
) B
JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
ORDER BY B.PRICE

# WHERE
# GROUP BY
# HAVING
# ORDER BY
# LIMIT