-- 코드를 작성해주세요

-- ITEM_INFO에서 RARITY가 RATE인 ITEM_ID를 가져옴
-- ITEM_TREE에서 PARENT_ITEM_ID가 ITEM_ID이어야 함
-- ITEM_INFO에서 ITEM_TREE에서 PARENT_ITEM_ID가 ITEM_ID인 ITEM_ID를 가져옴

SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (
    SELECT ITEM_ID
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IN (
        SELECT ITEM_ID
        FROM ITEM_INFO
        WHERE RARITY LIKE "RARE"
    )
)
ORDER BY ITEM_ID DESC


