-- 코드를 입력하세요
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE 20220801<=START_DATE AND START_DATE<20221101 AND CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE 20220801<=START_DATE AND START_DATE<20221101
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID)>=5
)
GROUP BY MONTH, CAR_ID
ORDER BY MONTH, CAR_ID DESC