-- 코드를 입력하세요
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(START_DATE) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE>=20220801 AND START_DATE<=20221031
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
) AND START_DATE>=20220801 AND START_DATE<=20221031
GROUP BY MONTH, CAR_ID
ORDER BY MONTH, CAR_ID DESC

# WHERE
# GROUP BY
# HAVING
# ORDER BY
# LIMIT