-- 코드를 작성해주세요
SELECT D.YEAR, D.YEAR_DEV - ED.SIZE_OF_COLONY AS YEAR_DEV, ED.ID
FROM ECOLI_DATA ED
JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY)AS YEAR_DEV
    FROM ECOLI_DATA
    GROUP BY YEAR
) D ON YEAR(ED.DIFFERENTIATION_DATE) = D.YEAR
ORDER BY D.YEAR, YEAR_DEV