-- 코드를 작성해주세요
SELECT SUM(G.SCORE) AS SCORE, G.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
    FROM HR_DEPARTMENT D
    JOIN HR_EMPLOYEES E ON D.DEPT_ID = E.DEPT_ID
    JOIN HR_GRADE G ON E.EMP_NO = G.EMP_NO
    GROUP BY G.EMP_NO
    ORDER BY SCORE DESC
    LIMIT 1
    
    
# 2022로 GROUP BY

# WHERE
# GROUP BY
# HAVING
# ORDER BY
# LIMIT